### ISSUE TITLE
No way to add dice now?

### ISSUE THREAD

**Issue by xXxDFAxXx** [Qubus0/diceRoller#13]
It's been a couple weeks since I last used this. The new interface looks much better. However, I don't see any way to add dice now. Tried in both Firefox and Chrome browsers.

**Comment by Qubus0** [comment]
Oh wow, no idea how that slipped through. One typo that matters when the system considers capital letters to be different. Thanks for the heads up - it's now fixed. Could you test it again? If it doesn't appear, you might have to force reload (Crtl+Shift+R)
